contact: null
contributors: null
creators: null
description: None
dosdp_tools_options: --obo-prefixes=true
edit_format: owl
export_formats:
- owl
- obo
- json
github_org: earthcubearchitecture-ecresourcereg
gzip_main: false
id: ecrro
import_group:
  directory: imports/
  disabled: false
  ids: null
  products:
  - description: null
    id: ro
    mirror_from: http://purl.obolibrary.org/obo/ro/core.owl
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: bfo
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: swo
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: obi
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: ncit
    mirror_from: null
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: dcat
    mirror_from: https://www.w3.org/ns/dcat.rdf
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: prov-o
    mirror_from: http://www.w3.org/ns/prov-o
    rebuild_if_source_changes: true
    robot_settings: null
  - description: null
    id: sio
    mirror_from: https://raw.githubusercontent.com/micheldumontier/semanticscience/master/ontology/sio/release/sio-release.owl
    rebuild_if_source_changes: true
    robot_settings: null
  rebuild_if_source_changes: true
import_pattern_ontology: false
license: Unspecified
namespaces: null
obo_format_options: ''
pattern_group: null
pattern_pipelines_group: null
primary_release: full
reasoner: ELK
release_artefacts:
- full
- base
repo: ecrro
report_fail_on: ERROR
robot_java_args: ''
robot_settings: null
robot_version: null
robotemplate_group: null
subset_group: null
title: Earth Cube Resource Registry Ontology
travis_emails: null
uribase: http://purl.obolibrary.org/obo
use_dosdps: false
